[package]
name = "STM32rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7"
cortex-m-rtic = "0.5"
embedded-hal = "0.2"
stm32f4 = "0.14"
